.TH "app.api_client.ApiError" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.api_client.ApiError \- Exception pour les erreurs d'API\&.  

.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de Exception\&.
.SH "Description détaillée"
.PP 
Exception pour les erreurs d'API\&. 

Exception personnalisée levée en cas d'erreur lors des communications avec les APIs oblosolutions\&.ch\&. 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
