.TH "app.pins_cm5" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.pins_cm5
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBGPIO_CHIP_PATH\fP = '/dev/gpiochip0'"
.br
.ti -1c
.RI "int \fBMUX_CS_4\fP = 2"
.br
.ti -1c
.RI "int \fBMUX_CS_3\fP = 3"
.br
.ti -1c
.RI "int \fBMUX_CS_2\fP = 7"
.br
.ti -1c
.RI "int \fBMUX_CS_1\fP = 8"
.br
.ti -1c
.RI "int \fBMUX_MOSI_DUMMY\fP = 10"
.br
.ti -1c
.RI "int \fBMUX_SCLK_DUMMY\fP = 11"
.br
.ti -1c
.RI "int \fBCM_24V_OUT_1\fP = 13"
.br
.ti -1c
.RI "int \fBCM_24V_SENSE_1\fP = 14"
.br
.ti -1c
.RI "int \fBCM_24V_OUT_2\fP = 15"
.br
.ti -1c
.RI "int \fBCM_24V_SENSE_2\fP = 16"
.br
.ti -1c
.RI "int \fBCMD_RELAY\fP = 17"
.br
.ti -1c
.RI "int \fBCS_ADC_DUMMY\fP = 18"
.br
.ti -1c
.RI "int \fBSPI_MISO_ADC_DMY\fP = 19"
.br
.ti -1c
.RI "int \fBSPI_MOSI_ADC_DMY\fP = 20"
.br
.ti -1c
.RI "int \fBSPI_SCLK_ADC_DMY\fP = 21"
.br
.ti -1c
.RI "int \fBADC_DRDY\fP = 22"
.br
.ti -1c
.RI "int \fBADC_START_SYNC\fP = 23"
.br
.ti -1c
.RI "int \fBADC_A0\fP = 24"
.br
.ti -1c
.RI "int \fBADC_A1\fP = 25"
.br
.ti -1c
.RI "int \fBFRONT_LED\fP = 27"
.br
.ti -1c
.RI "int \fBSPI0_BUS\fP = 0"
.br
.ti -1c
.RI "int \fBSPI1_BUS\fP = 1"
.br
.ti -1c
.RI "int \fBSPI0_DEV0\fP = 0"
.br
.ti -1c
.RI "int \fBSPI0_DEV1\fP = 1"
.br
.ti -1c
.RI "int \fBSPI1_DEV0\fP = 0"
.br
.ti -1c
.RI "int \fBSPI_MUX_SPEED_HZ\fP = 100000"
.br
.ti -1c
.RI "int \fBSPI_ADC_SPEED_HZ\fP = 100000"
.br
.in -1c
.SH "Documentation des variables"
.PP 
.SS "int app\&.pins_cm5\&.ADC_A0 = 24"

.SS "int app\&.pins_cm5\&.ADC_A1 = 25"

.SS "int app\&.pins_cm5\&.ADC_DRDY = 22"

.SS "int app\&.pins_cm5\&.ADC_START_SYNC = 23"

.SS "int app\&.pins_cm5\&.CM_24V_OUT_1 = 13"

.SS "int app\&.pins_cm5\&.CM_24V_OUT_2 = 15"

.SS "int app\&.pins_cm5\&.CM_24V_SENSE_1 = 14"

.SS "int app\&.pins_cm5\&.CM_24V_SENSE_2 = 16"

.SS "int app\&.pins_cm5\&.CMD_RELAY = 17"

.SS "int app\&.pins_cm5\&.CS_ADC_DUMMY = 18"

.SS "int app\&.pins_cm5\&.FRONT_LED = 27"

.SS "str app\&.pins_cm5\&.GPIO_CHIP_PATH = '/dev/gpiochip0'"

.SS "int app\&.pins_cm5\&.MUX_CS_1 = 8"

.SS "int app\&.pins_cm5\&.MUX_CS_2 = 7"

.SS "int app\&.pins_cm5\&.MUX_CS_3 = 3"

.SS "int app\&.pins_cm5\&.MUX_CS_4 = 2"

.SS "int app\&.pins_cm5\&.MUX_MOSI_DUMMY = 10"

.SS "int app\&.pins_cm5\&.MUX_SCLK_DUMMY = 11"

.SS "int app\&.pins_cm5\&.SPI0_BUS = 0"

.SS "int app\&.pins_cm5\&.SPI0_DEV0 = 0"

.SS "int app\&.pins_cm5\&.SPI0_DEV1 = 1"

.SS "int app\&.pins_cm5\&.SPI1_BUS = 1"

.SS "int app\&.pins_cm5\&.SPI1_DEV0 = 0"

.SS "int app\&.pins_cm5\&.SPI_ADC_SPEED_HZ = 100000"

.SS "int app\&.pins_cm5\&.SPI_MISO_ADC_DMY = 19"

.SS "int app\&.pins_cm5\&.SPI_MOSI_ADC_DMY = 20"

.SS "int app\&.pins_cm5\&.SPI_MUX_SPEED_HZ = 100000"

.SS "int app\&.pins_cm5\&.SPI_SCLK_ADC_DMY = 21"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
