.TH "app.test_spi_adc" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.test_spi_adc
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBtest_spi_adc\fP ()"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "app\&.test_spi_adc\&.test_spi_adc ()"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
