.TH "app.front_led_management.LedErrorIndicator" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.front_led_management.LedErrorIndicator \- Gestionnaire de LED avec patterns d'erreur\&.  

.SH SYNOPSIS
.br
.PP
.SS "Attributs publics statiques"

.in +1c
.ti -1c
.RI "float \fBBASE_BLINK_TIME\fP = 0\&.2"
.br
.ti -1c
.RI "float \fBCYCLE_TIME\fP = 10\&.0"
.br
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de LED avec patterns d'erreur\&. 

Classe pour contrôler une LED frontale avec différents patterns de clignotement selon les états du système\&. Supporte les modes normal, standby, séquence en cours et divers patterns d'erreur avec clignotements codifiés\&. 
.SH "Documentation des données membres"
.PP 
.SS "float app\&.front_led_management\&.LedErrorIndicator\&.BASE_BLINK_TIME = 0\&.2\fR [static]\fP"

.SS "float app\&.front_led_management\&.LedErrorIndicator\&.CYCLE_TIME = 10\&.0\fR [static]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
