.TH "Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fB__init__\&.py\fP"
.br
.ti -1c
.RI "fichier \fBadc_ads124s08\&.py\fP"
.br
.RI "Driver pour l'ADC ADS124S08 avec communication SPI\&. "
.ti -1c
.RI "fichier \fBapi_client\&.py\fP"
.br
.RI "Client API pour les services oblosolutions\&.ch\&. "
.ti -1c
.RI "fichier \fBconfig_loader\&.py\fP"
.br
.RI "Chargeur de configuration JSON pour le système de mesure\&. "
.ti -1c
.RI "fichier \fBfront_led_management\&.py\fP"
.br
.RI "Gestionnaire de LED frontale avec patterns d'erreur\&. "
.ti -1c
.RI "fichier \fBhw_mux_adg731\&.py\fP"
.br
.RI "Pilote pour multiplexeur ADG731 via interface SPI\&. "
.ti -1c
.RI "fichier \fBhw_tmux1204\&.py\fP"
.br
.RI "Pilote pour multiplexeur TMUX1204 de sélection de résistance de référence\&. "
.ti -1c
.RI "fichier \fBmain\&.py\fP"
.br
.RI "Système de mesure et simulation de température\&. "
.ti -1c
.RI "fichier \fBmesure_24v_dry_contact\&.py\fP"
.br
.RI "Module de test des entrées/sorties 24V pour contacts secs\&. "
.ti -1c
.RI "fichier \fBpins_cm5\&.py\fP"
.br
.RI "Mapping GPIO et SPI fixés pour la plateforme CM5\&. "
.ti -1c
.RI "fichier \fBresistance_mapping\&.py\fP"
.br
.RI "Mapping des résistances TMUX par type de sonde de température\&. "
.ti -1c
.RI "fichier \fBresistance_simulation\&.py\fP"
.br
.RI "Module pour commander le MUX de simulation de résistance\&. "
.ti -1c
.RI "fichier \fBsensor_profiles\&.py\fP"
.br
.RI "Profils capteurs extraits de 'Calcul ADC\&.xlsx' (Feuil1)\&. "
.ti -1c
.RI "fichier \fBtemperature_conversion\&.py\fP"
.br
.RI "Module de conversion résistance/température via interpolation linéaire\&. "
.ti -1c
.RI "fichier \fBtemperature_simulation\&.py\fP"
.br
.RI "Module de calcul de température simulée selon formule prédictive\&. "
.ti -1c
.RI "fichier \fBtest_lm70_compatible\&.py\fP"
.br
.ti -1c
.RI "fichier \fBtest_spi_adc\&.py\fP"
.br
.in -1c
