.TH "Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/webui" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/webui
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fB__init__\&.py\fP"
.br
.ti -1c
.RI "fichier \fBwebui_server\&.py\fP"
.br
.RI "Serveur web pour interface utilisateur de configuration\&. "
.in -1c
