.TH "Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/config_module" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/config_module
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fB__init__\&.py\fP"
.br
.ti -1c
.RI "fichier \fBcm5_config\&.py\fP"
.br
.RI "Configuration matérielle pour plateforme CM5\&. "
.in -1c
