.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/front_led_management.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/front_led_management.py \- Gestionnaire de LED frontale avec patterns d'erreur\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBapp\&.front_led_management\&.LedErrorIndicator\fP"
.br
.RI "Gestionnaire de LED avec patterns d'erreur\&. "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.front_led_management\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBapp\&.front_led_management\&.create_led_indicator\fP (gpio_chip_path, led_pin)"
.br
.RI "Factory function pour créer une instance \fBLedErrorIndicator\fP\&. "
.in -1c
.SH "Description détaillée"
.PP 
Gestionnaire de LED frontale avec patterns d'erreur\&. 

Ce module fournit une classe pour gérer les clignotements et états de la LED frontale avec différents patterns d'erreur\&. Supporte les modes continus, les clignotements d'erreur et la gestion thread-safe des patterns LED\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
