.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/hw_mux_adg731.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/hw_mux_adg731.py \- Pilote pour multiplexeur ADG731 via interface SPI\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBapp\&.hw_mux_adg731\&.Adg731MuxSpi\fP"
.br
.RI "Pilote SPI pour multiplexeurs ADG731\&. "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.hw_mux_adg731\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBapp\&.hw_mux_adg731\&.adg731_ctrl_byte\fP (address, enable=True)"
.br
.RI "Génère le byte de contrôle pour l'ADG731\&. "
.in -1c
.SH "Description détaillée"
.PP 
Pilote pour multiplexeur ADG731 via interface SPI\&. 

Ce module fournit un pilote pour contrôler les multiplexeurs ADG731 via l'interface SPI0\&. Supporte jusqu'à 4 cartes avec 32 canaux chacune\&. Gère la configuration SPI et l'envoi des commandes de contrôle pour la sélection des canaux\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
