.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/mesure_24v_dry_contact.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/mesure_24v_dry_contact.py \- Module de test des entrées/sorties 24V pour contacts secs\&.  

.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.mesure_24v_dry_contact\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBapp\&.mesure_24v_dry_contact\&.test_24v_dry_contact\fP ()"
.br
.RI "Test des contacts secs I/O 24V\&. "
.ti -1c
.RI "\fBapp\&.mesure_24v_dry_contact\&.get_dry_contact_status\fP ()"
.br
.RI "Retourne l'état actuel des contacts secs\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.CM_24V_OUT_1\fP = 13"
.br
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.CM_24V_SENSE_1\fP = 14"
.br
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.CM_24V_OUT_2\fP = 15"
.br
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.CM_24V_SENSE_2\fP = 16"
.br
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.io_24v_ch1_ok\fP = 0"
.br
.ti -1c
.RI "int \fBapp\&.mesure_24v_dry_contact\&.io_24v_ch2_ok\fP = 0"
.br
.in -1c
.SH "Description détaillée"
.PP 
Module de test des entrées/sorties 24V pour contacts secs\&. 

Ce module fournit des fonctions pour tester et valider les contacts secs via les interfaces I/O 24V\&. Permet de détecter l'état des contacts (ouvert/fermé) sur deux canaux indépendants avec gestion des GPIO et temporisations appropriées\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
