.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/pins_cm5.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/pins_cm5.py \- Mapping GPIO et SPI fixés pour la plateforme CM5\&.  

.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.pins_cm5\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBapp\&.pins_cm5\&.GPIO_CHIP_PATH\fP = '/dev/gpiochip0'"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_CS_4\fP = 2"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_CS_3\fP = 3"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_CS_2\fP = 7"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_CS_1\fP = 8"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_MOSI_DUMMY\fP = 10"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.MUX_SCLK_DUMMY\fP = 11"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CM_24V_OUT_1\fP = 13"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CM_24V_SENSE_1\fP = 14"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CM_24V_OUT_2\fP = 15"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CM_24V_SENSE_2\fP = 16"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CMD_RELAY\fP = 17"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.CS_ADC_DUMMY\fP = 18"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI_MISO_ADC_DMY\fP = 19"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI_MOSI_ADC_DMY\fP = 20"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI_SCLK_ADC_DMY\fP = 21"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.ADC_DRDY\fP = 22"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.ADC_START_SYNC\fP = 23"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.ADC_A0\fP = 24"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.ADC_A1\fP = 25"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.FRONT_LED\fP = 27"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI0_BUS\fP = 0"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI1_BUS\fP = 1"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI0_DEV0\fP = 0"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI0_DEV1\fP = 1"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI1_DEV0\fP = 0"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI_MUX_SPEED_HZ\fP = 100000"
.br
.ti -1c
.RI "int \fBapp\&.pins_cm5\&.SPI_ADC_SPEED_HZ\fP = 100000"
.br
.in -1c
.SH "Description détaillée"
.PP 
Mapping GPIO et SPI fixés pour la plateforme CM5\&. 

Ce module définit tous les assignements de broches GPIO et les paramètres SPI fixes pour la carte CM5\&. Ces constantes ne doivent pas être modifiées via la configuration utilisateur car elles correspondent au routage matériel de la carte\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
