.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/sensor_profiles.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/sensor_profiles.py \- Profils capteurs extraits de 'Calcul ADC\&.xlsx' (Feuil1)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.sensor_profiles\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBapp\&.sensor_profiles\&.get_profile\fP (sensor_name)"
.br
.RI "Récupère le profil de configuration ADC pour un capteur donné\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dict \fBapp\&.sensor_profiles\&.SENSOR_PROFILES\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Profils capteurs extraits de 'Calcul ADC\&.xlsx' (Feuil1)\&. 

Ce module contient les profils de configuration pour différents types de capteurs de température avec leurs paramètres ADC optimisés (Rref, IDAC, PGA) et leurs tables de conversion température/résistance\&. Les données proviennent des calculs d'optimisation du fichier Excel de référence\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
