.TH "C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/temperature_conversion.py" 3 "2510_RegulationChauffage" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebi/Documents/2510_RegulationChauffage/doc/9.SoftWare/Doxygen/src/app/temperature_conversion.py \- Module de conversion résistance/température via interpolation linéaire\&.  

.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI "namespace \fBapp\fP"
.br
.ti -1c
.RI "namespace \fBapp\&.temperature_conversion\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.resistance_to_temperature\fP (resistance, table)"
.br
.RI "Convertit une résistance mesurée en température via interpolation linéaire\&. "
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.resistance_to_temperature_dynamic\fP (resistance, sensor)"
.br
.RI "Convertit une résistance mesurée en température pour un capteur donné\&. "
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.temperature_to_resistance_dynamic\fP (temperature, sensor)"
.br
.RI "Convertit une température en résistance pour un capteur donné (conversion inverse)\&. "
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.convert_temperature_to_resistance\fP (temperature, probe_type)"
.br
.RI "Fonction de conversion principale pour la simulation de résistance\&. "
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.get_supported_probe_types\fP ()"
.br
.RI "Retourne la liste des types de sondes supportés\&. "
.ti -1c
.RI "\fBapp\&.temperature_conversion\&.validate_temperature_range\fP (temperature, probe_type)"
.br
.RI "Valide si une température est dans la plage supportée par une sonde\&. "
.in -1c
.SH "Description détaillée"
.PP 
Module de conversion résistance/température via interpolation linéaire\&. 

Ce module fournit les fonctions de conversion bidirectionnelle entre résistance mesurée et température pour différents types de capteurs\&. Utilise l'interpolation linéaire sur les tables de calibration et supporte la conversion inverse pour la simulation de résistance\&. 
.PP
\fBAuteur\fP
.RS 4
Léo Mendes @project 2510_RegulationsChauffage @Mandant Oblo_solution 
.RE
.PP
\fBDate\fP
.RS 4
2025-09-18 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0\&.0 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2025 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour 2510_RegulationChauffage à partir du code source\&.
